// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsTJtbOeRL0xd-NYMbIhNeT2G5cBoUfOs',
    appId: '1:915072214362:web:314fcc8c968e4f26103f63',
    messagingSenderId: '915072214362',
    projectId: 'toonity-e0160',
    authDomain: 'toonity-e0160.firebaseapp.com',
    storageBucket: 'toonity-e0160.firebasestorage.app',
    measurementId: 'G-V0LS4L48J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMt0iVcz17jR7CWsG_gfFfkhyKzhCLhXA',
    appId: '1:915072214362:android:acd24ad4cffb7ff0103f63',
    messagingSenderId: '915072214362',
    projectId: 'toonity-e0160',
    storageBucket: 'toonity-e0160.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDGdXoxD9IGWhcECUximEDzzW6fBUECqE',
    appId: '1:915072214362:ios:e3f55346dfc51c9f103f63',
    messagingSenderId: '915072214362',
    projectId: 'toonity-e0160',
    storageBucket: 'toonity-e0160.firebasestorage.app',
    iosBundleId: 'com.toonity.app.toonity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDGdXoxD9IGWhcECUximEDzzW6fBUECqE',
    appId: '1:915072214362:ios:e3f55346dfc51c9f103f63',
    messagingSenderId: '915072214362',
    projectId: 'toonity-e0160',
    storageBucket: 'toonity-e0160.firebasestorage.app',
    iosBundleId: 'com.toonity.app.toonity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsTJtbOeRL0xd-NYMbIhNeT2G5cBoUfOs',
    appId: '1:915072214362:web:4b77596a02579fa3103f63',
    messagingSenderId: '915072214362',
    projectId: 'toonity-e0160',
    authDomain: 'toonity-e0160.firebaseapp.com',
    storageBucket: 'toonity-e0160.firebasestorage.app',
    measurementId: 'G-5SYFW7K84J',
  );
}
